import { Category, Product, Coupon, Review, StoreSettings, User } from '../src/types';

export const initialCategories: Category[] = [
  {
    id: 'cat-luxury-pret',
    name: 'Luxury Pret',
    slug: 'luxury-pret',
    description: 'Impeccably tailored ready-to-wear silhouettes featuring pure silk, organza, and delicate resham embroidery.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    order: 1,
    isActive: true,
    productCount: 4,
  },
  {
    id: 'cat-festive-formals',
    name: 'Festive Formals',
    slug: 'festive-formals',
    description: 'Opulent festive ensembles adorned with intricate zardozi, tilla, and mukesh work for wedding festivities.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
    order: 2,
    isActive: true,
    productCount: 3,
  },
  {
    id: 'cat-unstitched',
    name: 'Festive Unstitched',
    slug: 'festive-unstitched',
    description: '3-Piece pure raw silk, lawn, and karandi unstitched fabrics accompanied by digital printed silk dupattas.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=900&q=80',
    order: 3,
    isActive: true,
    productCount: 2,
  },
  {
    id: 'cat-bridal',
    name: 'Bridal Couture',
    slug: 'bridal-couture',
    description: 'Masterfully hand-crafted heirloom lehengas, peshwas, and ghararas made to order for the discerning bride.',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=900&q=80',
    order: 4,
    isActive: true,
    productCount: 2,
  },
  {
    id: 'cat-menswear',
    name: 'Men’s Sartorial',
    slug: 'mens-sartorial',
    description: 'Classic raw silk kurtas, tailored waistcoats, and regal sherwanis cut with timeless Pakistani precision.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
    order: 5,
    isActive: true,
    productCount: 2,
  },
  {
    id: 'cat-shawls',
    name: 'Heirloom Shawls',
    slug: 'heirloom-shawls',
    description: 'Pure micro-velvet and authentic Kashmiri pashmina shawls hand-embroidered with antique tilla borders.',
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=80',
    order: 6,
    isActive: true,
    productCount: 2,
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-gul-e-dawood',
    title: 'Gul-e-Dawood Hand-Embroidered Raw Silk Ensemble',
    slug: 'gul-e-dawood-raw-silk-ensemble',
    shortDescription: 'Deep emerald 3-piece raw silk suit featuring intricate antique zardozi neckline and pure organza foil dupatta.',
    description: 'A masterpiece of Pakistani craftsmanship from our Festive Pret ’26 collection. Crafted from 80gm pure Rawaan silk in rich jewel emerald, this shirt is adorned with hand-worked dabka, nakshi, and marori embroidery along the neckline and cuffs. Paired with straight tailored silk culottes and an airy organza dupatta finished with gold kiran edging.',
    categoryId: 'cat-luxury-pret',
    categoryName: 'Luxury Pret',
    price: 24500,
    salePrice: 21900,
    sku: 'ZQ-PRT-001',
    stock: 14,
    fabric: 'Pure Raw Silk 80gm',
    embroideryWork: 'Handcrafted Zardozi, Tilla & Marori',
    pieceCount: '3-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    colors: ['Emerald Green', 'Royal Crimson', 'Midnight Teal'],
    rating: 4.9,
    reviewsCount: 28,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    status: 'active',
    weightKg: 0.9,
    dimensionsCm: '35x28x6',
    seoTitle: 'Gul-e-Dawood Raw Silk 3-Piece Pakistani Luxury Pret',
    seoDescription: 'Buy authentic Pakistani raw silk 3-piece suit with hand-worked zardozi embroidery. Cash on Delivery across Pakistan.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-noor-e-jahan',
    title: 'Noor-e-Jahan Chiffon Festive 3-Piece Formals',
    slug: 'noor-e-jahan-chiffon-festive-formals',
    shortDescription: 'Champagne gold chiffon peshwas with silver gota kinari, badla embellishments, and tonal churidar.',
    description: 'Evoking the timeless romance of Mughal court aesthetics, Noor-e-Jahan features 16 flared kalis in feather-light pure crinkle chiffon. Glistening badla and mukesh sit atop hand-cut floral appliqués. Comes complete with a structured inner slip, stretch churidar, and an elaborately scalloped 2.75-meter dupatta.',
    categoryId: 'cat-festive-formals',
    categoryName: 'Festive Formals',
    price: 32000,
    sku: 'ZQ-FST-002',
    stock: 8,
    fabric: 'Pure Crinkle Chiffon',
    embroideryWork: 'Silver Gota, Badla, Mukesh & Pearl Spangles',
    pieceCount: '3-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['S', 'M', 'L', 'Custom'],
    colors: ['Champagne Gold', 'Blush Rose'],
    rating: 5.0,
    reviewsCount: 19,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    status: 'active',
    weightKg: 1.1,
    dimensionsCm: '38x30x8',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-mehtab-velvet',
    title: 'Mehtab Velvet Embroidered Shawl & Kurta Set',
    slug: 'mehtab-velvet-embroidered-shawl-kurta',
    shortDescription: 'Plum Italian micro-velvet straight silhouette accompanied by an intricately embroidered heavy velvet shawl.',
    description: 'Designed for high-winter weddings in Lahore and Islamabad, the Mehtab set combines regal warmth with sheer grandeur. Cut from premium 9000-grade Italian micro-velvet, the kurta features delicate resham thread-work at the hem. The crowning jewel is the 2.5-yard heavy velvet shawl blanketed in antique gold tilla and framed with kiran fringe.',
    categoryId: 'cat-shawls',
    categoryName: 'Heirloom Shawls',
    price: 28500,
    salePrice: 24900,
    sku: 'ZQ-SHW-003',
    stock: 5,
    fabric: '9000 Italian Micro Velvet',
    embroideryWork: 'Antique Gold Tilla, Resham & Sequence',
    pieceCount: '2-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Deep Plum', 'Imperial Navy', 'Forest Green'],
    rating: 4.8,
    reviewsCount: 34,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    status: 'active',
    weightKg: 1.6,
    dimensionsCm: '42x32x10',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-zeb-un-nisa-lehenga',
    title: 'Zeb-un-Nisa Heavily Embellished Organza Lehenga',
    slug: 'zeb-un-nisa-embellished-organza-lehenga',
    shortDescription: 'Crimson red kalidar bridal lehenga encrusted with swarovski crystals, cutdana, and zardozi medallions.',
    description: 'An heirloom bridal piece requiring over 280 hours of meticulous hand-needlework by master karigars in Old Lahore. The 18-kali voluminous organza skirt is lined with pure silk can-can for dramatic sweep. Features a jewel-encrusted sweetheart neckline choli and a 4-sided matha patti bridal veil.',
    categoryId: 'cat-bridal',
    categoryName: 'Bridal Couture',
    price: 68000,
    salePrice: 62000,
    sku: 'ZQ-BDL-004',
    stock: 3,
    fabric: 'Pure French Organza & Kimkhab',
    embroideryWork: 'Zardozi, Swarovski, Cutdana & Resham',
    pieceCount: '3-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1594824813587-2a6c8e31a106?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['S', 'M', 'L', 'Custom'],
    colors: ['Bridal Crimson', 'Rust Amber'],
    rating: 5.0,
    reviewsCount: 12,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    status: 'active',
    weightKg: 3.2,
    dimensionsCm: '50x40x15',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-afreen-lawn',
    title: 'Afreen Luxury Printed Lawn 3-Piece with Silk Dupatta',
    slug: 'afreen-luxury-printed-lawn-silk-dupatta',
    shortDescription: 'Premium Supima cotton lawn 3-piece unstitched suit with schiffli embroidered front and medium silk dupatta.',
    description: 'Perfect for Karachi and Punjab warm summers. 80-lea count combed Supima cotton lawn offering ultra-soft breathability. Complete with an embroidered organza neckline patch, schiffli daman border, dyed cambric cotton trousers, and a 100% pure silk digital printed dupatta.',
    categoryId: 'cat-unstitched',
    categoryName: 'Festive Unstitched',
    price: 14500,
    sku: 'ZQ-LWN-005',
    stock: 22,
    fabric: 'Premium 80-Lea Combed Lawn & Pure Silk',
    embroideryWork: 'Schiffli Chikankari with Laser Cutwork',
    pieceCount: '3-Piece Unstitched',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['Custom'],
    colors: ['Ivory Powder Blue', 'Lilac Orchid', 'Pale Sage'],
    rating: 4.7,
    reviewsCount: 42,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    status: 'active',
    weightKg: 0.7,
    dimensionsCm: '30x24x5',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-ranjha-kurta-waistcoat',
    title: 'Ranjha Royal Raw Silk Men’s Kurta & Waistcoat',
    slug: 'ranjha-royal-raw-silk-mens-kurta-waistcoat',
    shortDescription: 'Oatmeal raw silk tailored kurta pajama paired with an ivory gold embroidered Prince waistcoat.',
    description: 'Immaculately constructed menswear for weddings, Eid celebrations, and semi-formals. Cut from textured Pakistani raw silk with concealed plackets, mother-of-pearl buttons, and structured band collar. The accompanying waistcoat features self-tone geometric tilla embroidery and brass buttons.',
    categoryId: 'cat-menswear',
    categoryName: 'Men’s Sartorial',
    price: 19500,
    sku: 'ZQ-MEN-006',
    stock: 11,
    fabric: 'Pakistani Raw Silk 70gm',
    embroideryWork: 'Self-Tone Geometric Tilla & Hand Topstitching',
    pieceCount: '3-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: ['Oatmeal Ivory', 'Charcoal Slate', 'Midnight Black'],
    rating: 4.9,
    reviewsCount: 16,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    status: 'active',
    weightKg: 1.0,
    dimensionsCm: '36x28x7',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-qaus-e-qazah-pret',
    title: 'Qaus-e-Qazah Chikankari Cotton Net Pret',
    slug: 'qaus-e-qazah-chikankari-cotton-net-pret',
    shortDescription: 'Pastel pistachio cotton net kalidar kurti with fine lucknowi chikankari and pearl droplets.',
    description: 'A breezy, sophisticated statement piece ideal for day events and festive brunches. Delicate cotton net woven with silver threads, fully hand-worked in white shadow and jaali chikankari stitches. Finished with organza frills at the sleeves and hemline.',
    categoryId: 'cat-luxury-pret',
    categoryName: 'Luxury Pret',
    price: 18200,
    salePrice: 15900,
    sku: 'ZQ-PRT-007',
    stock: 9,
    fabric: 'Cotton Net & Viscose Cotton',
    embroideryWork: 'Lucknowi Chikankari & Pearl Droplets',
    pieceCount: '2-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pistachio Mist', 'Blush Peach'],
    rating: 4.8,
    reviewsCount: 22,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    status: 'active',
    weightKg: 0.6,
    dimensionsCm: '32x26x5',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-dastoor-sherwani',
    title: 'Dastoor Men’s Handcrafted Raw Silk Sherwani',
    slug: 'dastoor-mens-handcrafted-raw-silk-sherwani',
    shortDescription: 'Bespoke off-white raw silk groom sherwani with antique marori work along collar and cuffs.',
    description: 'The epitome of Pakistani groom elegance. Padded shoulders, customized canvas chest piece, and handcrafted metallic buttons. Hand-embroidered with classic Lahore filigree patterns in matte antique gold wire.',
    categoryId: 'cat-menswear',
    categoryName: 'Men’s Sartorial',
    price: 58000,
    sku: 'ZQ-MEN-008',
    stock: 4,
    fabric: 'Heavy Banarsi Raw Silk',
    embroideryWork: 'Matte Gold Marori & Zari Work',
    pieceCount: '2-Piece Stitched',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'Custom'],
    colors: ['Antique Ivory', 'Royal Cream'],
    rating: 5.0,
    reviewsCount: 8,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    status: 'active',
    weightKg: 1.8,
    dimensionsCm: '45x35x12',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-kashmiri-pashmina',
    title: 'Zardozi Handcrafted Pure Pashmina Kashmiri Shawl',
    slug: 'zardozi-handcrafted-pure-pashmina-kashmiri-shawl',
    shortDescription: '100% certified authentic Cashmere pashmina with 4-side zardozi borders and sozni needlework.',
    description: 'Crafted from the softest grade-A Cashmere fleece from the northern valleys. Features traditional paisley and chinar leaf motifs hand-embroidered over 4 months by master artisans.',
    categoryId: 'cat-shawls',
    categoryName: 'Heirloom Shawls',
    price: 42000,
    salePrice: 38000,
    sku: 'ZQ-SHW-009',
    stock: 6,
    fabric: '100% Pure Himalayan Pashmina',
    embroideryWork: 'Traditional Sozni & Antique Zari Border',
    pieceCount: '1-Piece Shawl',
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=1000&q=85',
    ],
    sizes: ['Custom'],
    colors: ['Black Onyx', 'Camel Fawn', 'Crimson Ruby'],
    rating: 4.9,
    reviewsCount: 15,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    status: 'active',
    weightKg: 0.45,
    dimensionsCm: '30x20x4',
    createdAt: new Date().toISOString(),
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'cp-eid2026',
    code: 'EID2026',
    discountType: 'percentage',
    discountValue: 15,
    minOrderAmount: 10000,
    maxDiscountAmount: 5000,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    timesUsed: 64,
    isActive: true,
  },
  {
    id: 'cp-welcome500',
    code: 'WELCOME500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderAmount: 5000,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 1000,
    timesUsed: 182,
    isActive: true,
  },
  {
    id: 'cp-sheikh10',
    code: 'SHEIKH10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 15000,
    maxDiscountAmount: 3500,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 200,
    timesUsed: 29,
    isActive: true,
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-gul-e-dawood',
    customerName: 'Ayesha Siddiqui',
    city: 'Lahore (DHA Phase 5)',
    rating: 5,
    comment: 'The raw silk quality is genuinely superior to high-street brands. The zardozi work has remarkable precision and the stitching was true to Pakistani RTW measurements. Received via TCS within 2 days with Cash on Delivery.',
    verifiedPurchase: true,
    date: '2026-03-01',
    status: 'approved',
  },
  {
    id: 'rev-2',
    productId: 'prod-gul-e-dawood',
    customerName: 'Zainab Farooq',
    city: 'Karachi (Clifton)',
    rating: 5,
    comment: 'Wore this to my cousin’s Mehndi and received non-stop compliments. The emerald shade is rich and royal. Excellent packaging in a sturdy hardboard luxury box.',
    verifiedPurchase: true,
    date: '2026-03-04',
    status: 'approved',
  },
  {
    id: 'rev-3',
    productId: 'prod-mehtab-velvet',
    customerName: 'Dr. Maryam Khan',
    city: 'Islamabad (F-7/2)',
    rating: 5,
    comment: 'The 9000-grade micro velvet is thick, lush, and warm. The tilla embroidery doesn’t scratch or snag. Truly an heirloom shawl!',
    verifiedPurchase: true,
    date: '2026-02-20',
    status: 'approved',
  },
  {
    id: 'rev-4',
    productId: 'prod-ranjha-kurta-waistcoat',
    customerName: 'Hamza Bilal',
    city: 'Rawalpindi (Bahria Town)',
    rating: 5,
    comment: 'Ordered for Eid namaz and family dawat. The tailored cut of the waistcoat sits impeccably. Very pleased with the COD service.',
    verifiedPurchase: true,
    date: '2026-02-28',
    status: 'approved',
  },
];

export const initialSettings: StoreSettings = {
  storeName: 'Sheikh Iqbal Cloth & Boutique Centre',
  tagline: 'Fine Heritage Cloth, Unstitched Silks & Bespoke Boutique Pret',
  contactEmail: 'concierge@sheikhiqbalboutique.com',
  contactPhone: '[PHONE NUMBER]',
  whatsappNumber: '[WHATSAPP NUMBER]',
  storeAddress: '[ADDRESS]',
  city: 'Pakistan',
  currency: 'PKR',
  freeShippingThreshold: 5000,
  flatShippingFee: 250,
  expressDeliveryFee: 450,
  codEnabled: true,
  codAdvanceVerification: false,
  jazzcashEnabled: true,
  easypaisaEnabled: true,
  raastEnabled: true,
  raastIban: 'PK92BAHL0001234567890102',
  announcementText: '✨ Festive 2026 Collection Live — Free Express Delivery across Pakistan on orders over Rs. 5,000 | Cash on Delivery Available',
};

export const initialUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'Muhammad Athar (Director)',
    email: 'admin@sheikhiqbal.pk',
    passwordHash: '',
    phone: '03001234567',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-demo-customer',
    name: 'Syeda Fatima',
    email: 'fatima.zahra@gmail.com',
    passwordHash: '',
    phone: '03218765432',
    role: 'customer',
    addresses: [
      {
        fullName: 'Syeda Fatima',
        phone: '03218765432',
        email: 'fatima.zahra@gmail.com',
        streetAddress: 'House 42-B, Sector G-11/3',
        city: 'Islamabad',
        province: 'Islamabad Capital Territory',
        postalCode: '44000',
        nearbyLandmark: 'Near Markaz Commercial Area',
        deliveryInstructions: 'Please ring bell and verify order with phone SMS before handover.',
      }
    ],
    createdAt: new Date().toISOString(),
  }
];
